//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyApartments.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuyApartments.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;Houses&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;HighEnd_1&quot;,
        ///      &quot;Interior&quot;: &quot;Del_Perro-Apt_20&quot;,
        ///      &quot;Price&quot;: 750000,
        ///      &quot;Location&quot;: {
        ///        &quot;x&quot;: -772.795,
        ///        &quot;y&quot;: 313.055,
        ///        &quot;z&quot;: 85.698
        ///      }
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;HighEnd_2&quot;,
        ///      &quot;Interior&quot;: &quot;Eclipse_Towers-Apt_31&quot;,
        ///      &quot;Price&quot;: 670000,
        ///      &quot;Location&quot;: {
        ///        &quot;x&quot;: -1442.957,
        ///        &quot;y&quot;: -544.699,
        ///        &quot;z&quot;: 34.742
        ///      }
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;HighEnd_3&quot;,
        ///      &quot;Interior&quot;: &quot;Eclipse_Towers-Apt_40&quot;,
        ///      &quot;Price&quot;: 670000,
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Houses {
            get {
                return ResourceManager.GetString("Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;Interiors&quot;: [
        ///    {
        ///      &quot;Coordinates&quot;: {
        ///        &quot;x&quot;: -1466.041,
        ///        &quot;y&quot;: -532.230,
        ///        &quot;z&quot;: 56.000
        ///      },
        ///      &quot;Name&quot;: &quot;Del_Perro-Apt_20&quot;
        ///    },
        ///    {
        ///      &quot;Coordinates&quot;: {
        ///        &quot;x&quot;: -790.000,
        ///        &quot;y&quot;: 336.000,
        ///        &quot;z&quot;: 207.000
        ///      },
        ///      &quot;Name&quot;: &quot;Eclipse_Towers-Apt_31&quot;
        ///    },
        ///    {
        ///      &quot;Coordinates&quot;: {
        ///        &quot;x&quot;: -764.000,
        ///        &quot;y&quot;: 321.000,
        ///        &quot;z&quot;: 220.000
        ///      },
        ///      &quot;Name&quot;: &quot;Eclipse_Towers-Apt_40&quot;
        ///    },
        ///    {
        ///      &quot;Coordinates&quot;: {
        ///        &quot;x&quot;: -790.000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Interiors {
            get {
                return ResourceManager.GetString("Interiors", resourceCulture);
            }
        }
    }
}
